export default {
  SET_CURRENT_LOCATION: "SET_CURRENT_LOCATION",
  SET_SELECTED_CITY_WEATHER_DATA: "SET_SELECTED_CITY_WEATHER_DATA",
  SET_SEARSH_VALUE: "SET_SEARSH_VALUE",
  SET_IS_FECHING: "SET_IS_FECHING",
  SET_IS_FECHING_LOCATION: "SET_IS_FECHING_LOCATION",
};
